db:
  host: "![AaBuFzwJs/6ZcAAsuUfvkg==]"
  instance: "![O8B47zunscs=]"
  port: "![Tv0ASXSMIqI=]"
  user: "![X8iT9Umr77M=]"
  password: "![LwmxEc/UK8o=]"

postgresqldb:
  url: "![feZL/zC/YV+N/uY3T+gQ07S86A6Xh7pW2QWrfTlJJx5P4hRoVw1gcLZGig0FIMxU]"
  user: "![fLN33XNXY03xI/8tLxU1kg==]"
  password: "![LwmxEc/UK8o=]"
