db:
  host: "![AaBuFzwJs/6ZcAAsuUfvkg==]"
  instance: "![O8B47zunscs=]"
  port: "![Tv0ASXSMIqI=]"
  user: "![X8iT9Umr77M=]"
  password: "![LwmxEc/UK8o=]"

postgresqldb:
  url: "![feZL/zC/YV+N/uY3T+gQ07S86A6Xh7pW2QWrfTlJJx5P4hRoVw1gcLZGig0FIMxU]"
  user: "![fLN33XNXY03xI/8tLxU1kg==]"
  password: "![LwmxEc/UK8o=]"


salesforce:
  username: "![D8LmGWpCKUOk3esw+jcRPVtrRI/+MU9AXDgUZNsqphM=]"
  password: "![2u207qH2y/FDBj7vapqsiQ==]"
  securityToken: "![rZIl1mDU4/ttk1p/vBKMslAhEySQmWtUI9kVOzDeGw4=]"
  
aws:
  keyId: "![OE52d0wB7hPhR96709ik7y++8C2ClTja]"
  secretKey: "![DqIzu3jBloDCNW+XfNkt/dtVjBE2xMsSA1DWgFRDNvUiKJWWOyFuG6XmxfnF0c60]"
  bucketName: "![zFsekTCnRJX3+zucrHoDSA==]"
